docker-containers:
	sudo docker ps -a

docker-images:
	sudo docker images

restart-apache:
	sudo systemctl restart httpd.service

restart-docker:
	sudo systemctl restart docker.socket

start-apache:
	sudo systemctl start httpd.service

start-docker:
	sudo systemctl start docker.socket

stop-apache:
	sudo systemctl stop httpd.service

stop-docker:
	sudo systemctl stop docker.socket

